### ISSUE TITLE
not working on Android phones

### ISSUE THREAD

**Issue by jcm102120** [nccgroup/nOBEX#1]
Hi,  I have not been having any success with the pbapclient against Android phones.  It works fine against all iphones i have tried.  
I did a hcidump and see that the phone replies to the obex request of type "x-bt/vcard-listing" and name "telecom/pb" with Not Acceptable.  This causes the python script to throw a TypeError.
I don't have a SIM in the phone but tried it with the SIM option just to be safe.  I was wondering if you had tested this against an Android phone with any success.
Thanks

**Comment by sultanqasim** [comment]
Which Android version are use you using? I used a Moto X Play running CyanogenMod 13 to test when I was developing this. I can take a look at your hcidump logs if you email them to me. My work email address in the commits should be fine.

**Comment by jcm102120** [comment]
I tried it on a Galaxy S3 running 4.4 and an S4 running 5.0.
It seems to be the "x-bt/vcard-listing" that the android phone does not like.  I commented out that part of the code and just sent the "x-bt/phonebook" type request and the phone responds ok.  I am not exactly clear on the difference between the two.

**Comment by jcm102120** [comment]
I'm going to close this as a phone issue rather than a coding issue.  I will look into it a little more.
Thanks!
